export enum CardTypeEnum {
  TODO = "TODO",
  DOINT = "DOING",
  DONE = "DONE",
}

export enum AlarmType {
  CREATE_PROJECT = "CREATE_PROJECT",
  CREATE_TODO = "CREATE_TODO",
  MOVE_DOING = "MOVE_DOING",
  MOVE_DONE = "MOVE_DONE",
  CREATE_COMMENT = "CREATE_COMMENT",
}
